### ISSUE TITLE
Not working with 20.5.370

### ISSUE THREAD

**Issue by jeel23** [eglaubauf/egMatLib#5]
I've just upgraded to Houdini 20.5.370, I've kept everything as I did in previous version of houdini but I'm being presented with this error massage when viewing the matLib tab:

There is an error in the MatLib script.

Traceback (most recent call last):
     File "<stdin>", line 1, in <module>
     File "M:/STUDIO/Houdini/Mat Lib/egMatLib-main/python_panels/MatLib.pypanel", line 6, in createInterface
     same interface or of the interfaces menu are not allowed
     ^^^^^^^^^^^^^^^
     File "C:\Program Files\Side Effects Software\Houdini 20.5.370\python311\lib\site-packages-forced\shiboken2\files.dir\shibokensupport\feature.py", line 139, in _import
     return original_import(name, *args, **kwargs)
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ModuleNotFoundError: No module named 'egMatLib'

I have a pretty large material library from previous versions that can't be accessed now and would really appreciate any help or advice on the subject, thanks in advance.

**Comment by eglaubauf** [comment]
Hey @jeel23 

I just added support for Houdini 20.5. Could you check if this works for you now? 


Best, 
E

**Comment by jeel23** [comment]
Works like a charm! Thanks for your help!
